language: python
python: 3.5
env:
- TOXENV=py27
- TOXENV=py34
- TOXENV=py35
install:
- pip install -U tox
script:
- tox
notifications:
  slack:
    rooms:
      secure: Pf/lRKLUnEEFmjqQTetOjuLl1+es51ukyucDlV1k3boZUB2deIgFRFasflyJOUDq22YAh48iWyu4fDrUGi6umOlbzWcwv8f8yA9U6RG7u5k2JcWnqZRiQyxe8fLMcyvZse27ibP3yNFWHR1ZULAY1KomxYTghFOt4axz4qXMuZv7p++Btqxm9b6+wu2YhoqeNuCiZtQzakDH6YkD1r1c8z2rN55YVC7jTMQ3tsLGvWsVLvl6pcm26VQHW0zVEmnrlCa6o3sE16DDDSjc1OpxVYo7l+BwhBs0IdRltVcMEbLoJw3YrGjLNii5ZPIIJ7hBQgnoQvjeVYwfp4SzU995C1sjTYhaPq8Fi2sB63CeLCCKmSk4GbKp77S9R7+oA2vdz/9NOxGrmKgbHbiQIsmJU8vRZ/6krWKqVknlco2gv504lSs8Hk0NX/NaTs5rR205Nqo4hxyramE0+Olacp6MgNC7jB0tmYccVMdSOmXmu/OBwVbzfzdtzLm1ioeGjBy1hEMP2Fi/Tzq2MNrSxh9Vp78xetMAAoPnLYg+ehseFV4TMYrf/meJEZL/o/iSwRDNKw1JDsyx0oXKkvmg06o0M2rxONhaAjLO4VPErhDavhe+SnahcRd8VW9+RRlCMyu/4OiEfZXyiVF8szDlGpItN3EuivP5dAR1Z1WbPlS9TE4=
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: crim-ca
  password:
    secure: OPVN84qLimQt7BY/lMS0bK/TzZgRxPSQxkbzkwoQ3jMCHCCg5gcSC3OnivyCq3tb7zhf/1szNHhV2rA15KakFzdNDJSvKhXexeLkU3TcOEkwUYBPQmUaGfpF5Vy53zerPdxRlOUQegg0oYYXKVMDN4cJ5vydHToaiPYiDwzV8sGYpNmKFdiO+nEJ2Sze6BrorAUJVYBbUmeBk+XqsyeeYwqtuUESZJyVvhwcjIWwNUz1yaysbN6mMhuxsmybqTwWkU7JOPK91gKrSWo96Oom9eTQ/Yqvq8sKsz58CzkZm7OLzDEtX6yjs3jZzuEHkMSwGWY3mahMuafflyFqs+q5wj/i1/NcXdWs01GXKjCUmsn4qUE4Nvpw05QKuPPcVr6BLCDk9bFHfyMlvQhHqB81IA0LqBw5Y1lP+HboNHmzlp0LtGcxgcvOq/96XL+HzPGWbi2rvAwof+ED2va/KS1xfOcXrOgXauFESLRbEAgtE04idFBtkT1Hcvaaom5eBd2K43bsn+pVkRG/YeYDuZMdfVwZDf1YDJjTD/pV2fczXgcgrsfSh4ld/WTQ1sAjnxoZHypQ5Xg8NKhrKGubhucHzWZZ6YwMgG5dMlDDRGoj+ERkZ7zJMO4wTBolIfiyG2T8gYQvqXrnViHD8k6tDR1eO74TeCLQYXYcPWkPKWVouDw=
  on:
    tags: true
